### ISSUE TITLE
✨ 유저 생성 기능 추가

### ISSUE THREAD

**Issue by jjikky** [jjikky/retro-backend#11]
### ✨ 진행할 작업 설명

```markdown
유저 생성 기능 추가
```

### 🚀 TODO

- [x] 유저 리포지토리 인터페이스 및 구현체 추가
- [x] 유저 도메인과 persistence 간 매핑 로직 구현
- [x] UsersModule 수정 및 User 관계형 퍼시스턴스 모듈 추가
- [x] DeepPartial 및 OrNever 타입 유틸리티 추가
- [x] tsconfig에 src 경로 별칭 설정 추가
