### ISSUE TITLE
✨ 세션 모듈 세팅

### ISSUE THREAD

**Issue by jjikky** [jjikky/retro-backend#13]
### ✨ 진행할 작업 설명

```markdown
세션 모듈 세팅
```

### 🚀 TODO

- [x] 세션 엔티티, 도메인 모델 정의
- [x] 세션 리포지토리 인터페이스 및 구현체 추가
- [x] 세션 서비스 로직 구현
