### ISSUE TITLE
✨ 유저 도메인 세팅

### ISSUE THREAD

**Issue by jjikky** [jjikky/retro-backend#3]
### ✨ 진행할 작업 설명

```markdown
유저 도메인 세팅
```

### 🚀 TODO

- [x] 유저 controller, service, module 추가
- [x] 유저 관련 dto 추가
- [x] 유저 엔티티 추가
