### ISSUE TITLE
✨ mySQL & typeORM 세팅

### ISSUE THREAD

**Issue by jjikky** [jjikky/retro-backend#5]
### ✨ 진행할 작업 설명

```markdown
mySQL & typeORM 세팅
```

### 🚀 TODO

- [x] mySQL 도커 컴포즈 파일 추가
- [x] MySQL, typeORM 종속성 추가
- [x] MySQL, typeORM  설정 파일 추가 및 연결
