### ISSUE TITLE
✨ 파일 모듈 세팅

### ISSUE THREAD

**Issue by jjikky** [jjikky/retro-backend#9]
### ✨ 진행할 작업 설명

```markdown
파일 모듈 세팅, 생성 및 조회 로직 구현
local, s3, s3-presigned로 분리
```

### 🚀 TODO

- [x] 파일 모듈 설정 및 환경 분리
- [x] local, s3, s3-presigned별 모듈 및 관련 컨트롤러, 서비스, dto 추가
- [x] 파일 엔티티 추가 및 s3 presigned url 생성 로직 구현
- [x] 파일 도메인 및 퍼시스턴트 매퍼 구현
- [x] gitignore에 로컬 파일 저장 폴더 추가
- [x] Nullable 타입 유틸리티 추가
